config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies, only: [:index, :show]
  resources :actors, only: [:index, :show]
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :movie_locations
  has_many :movies, through: :movie_locations
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_actors
  has_many :actors, through: :movie_actors
  has_many :movie_locations
  has_many :locations, through: :movie_locations
  has_many :reviews
  has_many :users, through: :reviews

  def update_average_rating!
    avg_rating = reviews.average(:stars)
    update_column(:average_rating, avg_rating)
  end
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_location.rb
class MovieLocation < ApplicationRecord
  belongs_to :movie
  belongs_to :location
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  after_save :update_movie_average_rating
  after_destroy :update_movie_average_rating


  def update_movie_average_rating
    UpdateAverageRatingJob.perform_later(movie.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :movies, through: :reviews
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    if params[:search]
      @actors = Actor.where("name LIKE ?", "%#{params[:search]}%").page(params[:page]).per(50)
    else
      @actors = Actor.page(params[:page]).per(50)
    end
  end

  def show
    @actor = Actor.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.order(average_rating: :desc, title: :asc).page(params[:page]).per(50)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/index.html.erb
<h1>Actors</h1>

<%= form_with url: actors_path, method: :get, local: true do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<% if @actors.any? %>
  <ul>
    <% @actors.each do |actor| %>
      <li><%= link_to actor.name, actor_path(actor) %></li>
    <% end %>
  </ul>

  <%= paginate @actors %>
<% else %>
  <p>No actors found.</p>
<% end %>

app/views/actors/show.html.erb
<h1><%= @actor.name %></h1>

<h2>Movies</h2>
<ul>
  <% @actor.movies.each do |movie| %>
    <li><%= link_to movie.title, movie_path(movie) %></li>
  <% end %>
</ul>

<%= link_to 'Back to Search', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Year</th>
      <th>Director</th>
      <th>Country</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie_path(movie) %></td>
        <td><%= truncate(movie.description, length: 100) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director %></td>
        <td><%= movie.country %></td>
        <td><%= movie.average_rating || 'None' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @movies %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p><strong>Description:</strong> <%= @movie.description %></p>
<p><strong>Year:</strong> <%= @movie.year %></p>
<p><strong>Director:</strong> <%= @movie.director %></p>
<p><strong>Country:</strong> <%= @movie.country %></p>
<p><strong>Average Rating:</strong> <%= @movie.average_rating || 'None' %></p>

<h2>Actors</h2>
<ul>
  <% @movie.actors.each do |actor| %>
    <li><%= link_to actor.name, actor_path(actor) %></li>
  <% end %>
</ul>

<h2>Filming Locations</h2>
<ul>
  <% @movie.locations.each do |location| %>
    <li><%= location.filming_location %></li>
  <% end %>
</ul>

<%= link_to 'Back to Movies', movies_path %>